### PR TITLE
db2 support

### PR DESCRIPTION
**Pull request by sola1tmy**

### CODE REVIEW

**Comment by sola1tmy** [comment]
@V3lop5 I cleaned up my code today and pushed the code here.
So now you can pull the code , change the db2 config and have a test.
There are some work need your help.
1. Some tests are still failed, most of them are about foreign key, index. 
2. Some tests are changed or ignored for db2, you may check them again.

Last, wish this pull request helps.

**Comment by V3lop5** [comment]
@sola1tmy what version of db2 are you using?
I'm using the docker image `ibmcom/db2:11.5.7.0`.

It was a bit tricky to get that docker version finally running.

I received an exception in this `org.jetbrains.exposed.DefaultsTest > testDefaultExpressions02` testcase and found the solution [here](https://stackoverflow.com/questions/22360721/com-ibm-db2-jcc-am-sqlexception-jcc10120119364-14-88-invalid-operation).

Also I had a hard time with that docker image because its takes a lot of time to initialize the database.

I'll create a patch tomorrow.

---

I suppose the foreign key and index tests fails, because db2 does not allow unique constraints over nullable columns. (For my understanding.)

For example `PlayerTable` in `CreateMissingTablesAndColumnsTests.kt` contains
```kotlin
        val username = varchar("username", 10).uniqueIndex().nullable()
```
and the test `org.jetbrains.exposed.sql.tests.shared.ddl.CreateMissingTablesAndColumnsTests#explicitFkNameIsExplicit` fails with 
```
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=USERNAME, DRIVER=4.31.10
org.jetbrains.exposed.exceptions.ExposedSQLException: com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=USERNAME, DRIVER=4.31.10
SQL: [ALTER TABLE PLAYER ADD CONSTRAINT PLAYER_USERNAME_UNIQUE UNIQUE (USERNAME)]
```
https://www.ibm.com/docs/en/db2/11.5?topic=constraints-unique
We might need to change unique constraints to unique indices.
As far as I know from AS/400 (or i5) this should allow unique over nullable columns.

**Comment by V3lop5** [comment]
@sola1tmy 

> In my impression, It's a wrong way, because the foreign key needs unique constraint.（I'm not very sure)

Thats absolutly true! We might spoke past each other.


See test `org.jetbrains.exposed.sql.tests.shared.ddl.CreateMissingTablesAndColumnsTests#explicitFkNameIsExplicit`

https://www.sqlerror.de/db2_sql_error_-542_sqlstate_42831.html

For my understanding only columns defined as NOT NULL can be used for PRIMARY KEY, UNIQUE CONSTRAINT or PARENT KEY (foreign key). 

So the Exposed definition is not allowed for db2:
```kotlin
val username = varchar("username", 10).uniqueIndex().nullable()
```

I guess we should disable these tests?

**Comment by sola1tmy** [comment]
@V3lop5 
My bad, I didn't describe it clearly.

> ```kotlin
> val username = varchar("username", 10).uniqueIndex().nullable()
> ```

This code you said can be fixed by unique index.But you will more failed tests because you can't create table with foreign key without a unique constraint.

You can try override createIndex like this 


    override fun createIndex(index: Index): String {
        if (index.unique) {
            return super.createIndex(index.copy(unique = false)).replace("CREATE INDEX", "CREATE UNIQUE INDEX")
        }
        return super.createIndex(index)
    }


Then run this test
`org.jetbrains.exposed.sql.tests.shared.entities.EntityTests#callLimitOnRelationDoesntMutateTheCachedValue`

Now, you should get the error 
` DB2 SQL Error: SQLCODE=-573, SQLSTATE=42890, SQLERRMC=FK_POSTS_CATEGORY__UNIQUEID;INST.CATEGORIES, DRIVER=4.31.10`

Now we know, UNIQUE CONSTRAINT disable `uniqueIndex().nullable()` and UNIQUE INDEX disable **table create with foreign key**. But in exposed we can not choose unique constraint or index right now.

Maybe we should throw an exception when people want to use  `uniqueIndex().nullable()`  for db2.

**Comment by sola1tmy** [comment]
@V3lop5 
My bad, I didn't describe it clearly.

> ```kotlin
> val username = varchar("username", 10).uniqueIndex().nullable()
> ```

This code you said can be fixed by unique index.But you will more failed tests because you can't create table with foreign key without a unique constraint.

You can try override createIndex like this 


    override fun createIndex(index: Index): String {
        if (index.unique) {
            return super.createIndex(index.copy(unique = false)).replace("CREATE INDEX", "CREATE UNIQUE INDEX")
        }
        return super.createIndex(index)
    }


Then run this test
`org.jetbrains.exposed.sql.tests.shared.DDLTests#testCompositeFKReferencingUniqueIndex`

Now, you should get the error 
`DB2 SQL Error: SQLCODE=-573, SQLSTATE=42890, SQLERRMC=FK_TABLEB_ID_A_ID_B__ID_A_ID_B;INST.TABLEA, DRIVER=4.31.10`

Now we know, UNIQUE CONSTRAINT disable `uniqueIndex().nullable()` and UNIQUE INDEX disable **table create with foreign key**. But in exposed we can not choose UNIQUE CONSTRAINT or UNIQUE INDEX right now.

Maybe we should throw an exception when people want to use  `uniqueIndex().nullable()`  for db2.

**Comment by sola1tmy** [comment]
@V3lop5 
My bad, I didn't describe it clearly.

> ```kotlin
> val username = varchar("username", 10).uniqueIndex().nullable()
> ```

This code you said can be fixed by unique index.But you will have more failed tests because you can't make a foreign key constraint column reference a nullable unique index column.（Sorry for my bad english, maybe try the test below is more clear)

You can try override createIndex like this 


    override fun createIndex(index: Index): String {
        if (index.unique) {
            return super.createIndex(index.copy(unique = false)).replace("CREATE INDEX", "CREATE UNIQUE INDEX")
        }
        return super.createIndex(index)
    }


Then run this test
`org.jetbrains.exposed.sql.tests.shared.DDLTests#testCompositeFKReferencingUniqueIndex`

Now, you should get the error 
`DB2 SQL Error: SQLCODE=-573, SQLSTATE=42890, SQLERRMC=FK_TABLEB_ID_A_ID_B__ID_A_ID_B;INST.TABLEA, DRIVER=4.31.10`

It seems that UNIQUE CONSTRAINT disable `uniqueIndex().nullable()` and UNIQUE INDEX disable **FK reference to the column**. But in exposed we can not choose UNIQUE CONSTRAINT or UNIQUE INDEX right now.

Maybe we should change the **Column.uniqueIndex()**  to **Column.uniqueConstraint()**,and keep the **Table.uniqueIndex**, so that they can work differently.But this idea have break changes.

**Comment by V3lop5** [comment]
I prefer the second option.

Sorry, got no time in the past two days. I ll merge this PR tomorrow & add my changes.

**Pull request merged**
